name: Daily Stock Analysis

on:
  schedule:
    # Her gün sabah 20:00'da çalışacak (UTC+3 için 06:00 UTC)
    - cron: '1 7 * * 1-5'  # Pazartesiden Cumaya
  workflow_dispatch:  # Manuel tetikleme için

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run analysis
      run: python em_band_indicator.py
      env:
        MAILJET_API_KEY: ${{ secrets.MAILJET_API_KEY }}
        MAILJET_API_SECRET: ${{ secrets.MAILJET_API_SECRET }}
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
